//
// Created by netanel on 30/03/2019.
//

#ifndef COMM_NETS_SHARED_H
#define COMM_NETS_SHARED_H

#define MAX_INCOMING_QUEUE 1
#define PORT_NUMBER 54321
#define WARMPUP_PACKET_SIZE 1024
#define MIN_WARMUP_CYCLES 100
#define PACKETS_PER_CYCLE 1000
#define SERVER_ADDRESS "127.0.0.1"


#endif //COMM_NETS_SHARED_H
